name: cryptotracker
description: An app made using the Flutter framework that allows users to track information for over 2000 cryptocurrencies
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  http:
  local_database:
  path_provider:
  charts_flutter:
  flutter_launcher_icons:
  web_socket_channel:
  auto_size_text:
  syncfusion_flutter_charts:
  url_launcher:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/platypus.png"
  image_path_android: "assets/icon/platypus2.png"
  image_path_ios: "assets/icon/platypus.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/fonts/MavenPro-Regular.ttf