name: cryptotracker
description: An app made using the Flutter framework that allows users to track information for over 2000 cryptocurrencies
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  local_database: ^1.2.0
  path_provider: ^2.0.2
  charts_flutter: ^0.11.0
  flutter_launcher_icons: ^0.9.2
  web_socket_channel: ^2.1.0
  auto_size_text: ^2.1.0
  syncfusion_flutter_charts: ^19.2.59
  url_launcher: ^6.0.9
  flutter_svg: ^0.22.0
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/platypus.png"
  image_path_android: "assets/icon/platypus2.png"
  image_path_ios: "assets/icon/platypus.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/fonts/MavenPro-Regular.ttf